#cloud-config

hostname: rancher

rancher:
  network:
    interfaces:
      eth*:
       dhcp: false
      eth0:
       address: 10.10.1.15/24
       gateway: 10.10.1.1
    dns:
     nameservers:
      - 10.10.1.10
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYebWIuuhwjHl2CvpOqnrsxMWaaoIll+2ab5Poxb49FsC+YC712RdRu0lN9qLMFIsUzli9V75JaSTUnQUMFTVZoMX4wuQYv1YwpG8Hl7bGjDmOyxMBXXFHbuQepoFfXk3h1faDf/+wVgnCdh2DtcWHcfigqOOBpDVFbzbR/wGciKLF5VGt0lBisBkBN1ta1gjmLFcON/6csEaBBjHd9NjiTIC2vqiGjtY2DFItC37UnMYhaUgFAHVsIWn+26hTMcUrNgQs+/hRkioMPGALRWol3W4+hECUXH5dZ0Uq2p/VC6DkgQJJj0jSMtMiXfYJKU6Pr6s18vQNjz/e2xts3Wwx andrewdavies@Andrews-MacBook-Pro.local
